apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-end-time-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 30
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cronjob-end-time-cronjob
              image: cronjob-end-time
